
//var myCacheVersion = "v.1.2.2025.10";






//https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#basic_architecture
const registerServiceWorker = async () => {
  if ("serviceWorker" in navigator) {
    try {
      const registration = await navigator.serviceWorker.register("/sw.js", {
        scope: "/",
      });
      if (registration.installing) {
        console.log("Service worker installing");
      } else if (registration.waiting) {
        console.log("Service worker installed");
  
    } else if (registration.active) {



}
    } catch (error) {

console.error(`Registration failed with ` + error);
    }
  }
};



registerServiceWorker();
swJsInstallFiles();



// fu hide file extension
function hideLinkExt(url){
var linkExtList = ["index.html", ".html"];
var newURL = url;

linkExtList.forEach((element) => {
newURL = newURL.replace(element, '');
});

return newURL;
}
//














function swJsInstallFiles(){

/*
// cache
//https://stackoverflow.com/questions/66529102/uncaught-in-promise-typeerror-failed-to-execute-cache-on-addall-request
//https://github.com/mdn/pwa-examples
self.addEventListener('install', (e) => {
e.waitUntil(caches.open("v.1.2.2025.10").then((cache) => cache.addAll(fileListArrFound)),);
});*/





// add files to cache
// cache
//https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll

self.addEventListener('install', (e) => {


// start check 404, file list 2
var fileListArr = ["/404.html",
"/all/index.html",
"/all/",
"/all/script.js",
"/audio/click2.mp3",
"/audio/",
"/audio/click.mp3",
"/audio/error.mp3",
"/audio/game-over.mp3",
"/audio/neutral.mp3",
"/audio/ok.mp3",
"/audio/rain.mp3",
"/audio/white-noise.mp3",
"/audio/win.mp3",
"/BingSiteAuth.xml",
"/css/a-backup-old.css",
"/css/",
"/css/auto.css",
"/css/dark.css",
"/css/d-blue.css",
"/css/d-forest.css",
"/css/d-green.css",
"/css/d-orange.css",
"/css/d-pink.css",
"/css/d-plum.css",
"/css/d-purple.css",
"/css/d-red.css",
"/css/d-sea.css",
"/css/d-slate.css",
"/css/d-violet.css",
"/css/d-yellow.css",
"/css/empty.css",
"/css/h-contrast-d.css",
"/css/h-contrast-l.css",
"/css/l-blue.css",
"/css/l-green.css",
"/css/light.css",
"/css/l-merino.css",
"/css/l-olive.css",
"/css/l-orange.css",
"/css/l-pink.css",
"/css/l-plum.css",
"/css/l-purple.css",
"/css/l-red.css",
"/css/l-sea.css",
"/css/l-seashell.css",
"/css/l-violet.css",
"/css/l-yellow.css",
"/css/main (copy 1).css",
"/css/main.css",
"/css/noscript.css",
"/css/o-blue.css",
"/css/od-blue.css",
"/css/od-brown.css",
"/css/od-forest.css",
"/css/od-gray.css",
"/css/od-green.css",
"/css/od-olive.css",
"/css/od-pink.css",
"/css/od-plum.css",
"/css/od-purple.css",
"/css/od-red.css",
"/css/od-sea.css",
"/css/od-slate.css",
"/css/od-violet.css",
"/css/od-yellow.css",
"/css/o-green.css",
"/css/o-lime.css",
"/css/o-mint.css",
"/css/o-olive.css",
"/css/o-orange.css",
"/css/o-pink.css",
"/css/o-plum.css",
"/css/o-purple.css",
"/css/o-red.css",
"/css/o-sea.css",
"/css/o-silver.css",
"/css/o-violet.css",
"/css/o-yellow.css",
"/css/rss.css",
"/css/style.css",
"/data/ads.json",
"/data/",
"/data/adsJsonVar.js",
"/data/agicountdown.json",
"/data/agicountdownJsonVar.js",
"/data/blog.json",
"/data/blogJsonVar.js",
"/data/BookData.json",
"/data/BookDataJsonVar.js",
"/data/guestbook.json",
"/data/guestbookJsonVar.js",
"/data/HowMuchDoesAWebsiteCost.json",
"/data/HowMuchDoesAWebsiteCostJsonVar.js",
"/data/iconsJsonVar.js",
"/data/keep.json",
"/data/keepJsonVar.js",
"/data/links.json",
"/data/linksJsonVar.js",
"/data/microblog.json",
"/data/microblogJsonVar.js",
"/data/music.json",
"/data/musicJsonVar.js",
"/data/news.json",
"/data/newsJsonVar.js",
"/data/notes.json",
"/data/notesJsonVar.js",
"/data/podcast.json",
"/data/podcastJsonVar.js",
"/data/quiz.json",
"/data/quizJsonVar.js",
"/data/quote.json",
"/data/quoteJsonVar.js",
"/data/radio.json",
"/data/radioJsonVar.js",
"/data/sitemapJsonVar.js",
"/data/tv.json",
"/data/tvJsonVar.js",
"/data/video.json",
"/data/videoJsonVar.js",
"/data/wiki.json",
"/data/wikiJsonVar.js",
"/data/word.json",
"/data/wordJsonVar.js",
"/data2/watchlist.csv",
"/data2/",
"/favicon.ico",
"/fonts/LICENSE.txt",
"/fonts/",
"/fonts/Roboto-Regular.ttf",
"/games/dice-9/index.html",
"/games/",
"/games/dice-9/",
"/games/dice-9/script.js",
"/games/dice-9/style.css",
"/games/guess-number-10/index.html",
"/games/guess-number-10/",
"/games/guess-number-10/script.js",
"/games/guess-number-10/style.css",
"/games/index.html",
"/games/lnnguage-learning-quiz-45/index.html",
"/games/lnnguage-learning-quiz-45/",
"/games/lnnguage-learning-quiz-45/script (copy 1).js",
"/games/lnnguage-learning-quiz-45/script.js",
"/games/lnnguage-learning-quiz-45/style.css",
"/games/memory-symbol-11/index.html",
"/games/memory-symbol-11/",
"/games/memory-symbol-11/script.js",
"/games/memory-symbol-11/style.css",
"/games/quiz-42/index.html",
"/games/quiz-42/",
"/games/quiz-42/script (copy 1).js",
"/games/quiz-42/script (copy 2).js",
"/games/quiz-42/script.js",
"/games/quiz-42/style.css",
"/games/rock-paper-scissors-67/index.html",
"/games/rock-paper-scissors-67/",
"/games/rock-paper-scissors-67/script.js",
"/games/rock-paper-scissors-67/style.css",
"/games/snake-12/index.html",
"/games/snake-12/",
"/games/snake-12/script.js",
"/games/snake-12/style.css",
"/games/spin-wheel-69/index.html",
"/games/spin-wheel-69/",
"/games/spin-wheel-69/script.js",
"/games/spin-wheel-69/style.css",
"/games/tic-tac-toe-13/index.html",
"/games/tic-tac-toe-13/",
"/games/tic-tac-toe-13/script (copy 1).js",
"/games/tic-tac-toe-13/script.js",
"/games/tic-tac-toe-13/style.css",
"/games/typing-speed-14/index.html",
"/games/typing-speed-14/",
"/games/typing-speed-14/script.js",
"/games/typing-speed-14/style.css",
"/games/typing-speed-keyborad-70/index.html",
"/games/typing-speed-keyborad-70/",
"/games/typing-speed-keyborad-70/script.js",
"/games/typing-speed-keyborad-70/style.css",
"/googlebb934aafeeb1ecb6.html",
"/img/404.png",
"/img/",
"/img/404.svg",
"/img/bg/binary-d.svg",
"/img/bg/",
"/img/bg/binary.svg",
"/img/bg/circle-d.svg",
"/img/bg/circle.svg",
"/img/bg/deco-paper-d.svg",
"/img/bg/deco-paper.svg",
"/img/bg/flower-2-d.png",
"/img/bg/flower-2.png",
"/img/bg/flower-d.png",
"/img/bg/flower.png",
"/img/bg/granite-d.png",
"/img/bg/granite.png",
"/img/bg/grid-d.png",
"/img/bg/grid.png",
"/img/bg/index-d.svg",
"/img/bg/index.svg",
"/img/bg/line-chaotic-d.svg",
"/img/bg/line-chaotic.svg",
"/img/bg/line-square-d.svg",
"/img/bg/line-square.svg",
"/img/bg/mondrian-d.svg",
"/img/bg/mondrian-oval-d.svg",
"/img/bg/mondrian-oval.svg",
"/img/bg/mondrian.svg",
"/img/bg/old/cave-d.png",
"/img/bg/old/",
"/img/bg/old/cave.png",
"/img/bg/old/cloth-d.png",
"/img/bg/old/cloth.png",
"/img/bg/old/line-horizontal-d.svg",
"/img/bg/old/line-horizontal.svg",
"/img/bg/old/maze-d.png",
"/img/bg/old/maze.png",
"/img/bg/old/old-wall-d.png",
"/img/bg/old/old-wall.png",
"/img/bg/old/soil-d.png",
"/img/bg/old/soil.png",
"/img/bg/old/wall-d.png",
"/img/bg/old/wall.png",
"/img/bg/old/wood-d-delme.svg",
"/img/bg/old/wood-delme.svg",
"/img/bg/shape-d.svg",
"/img/bg/shape.svg",
"/img/bg/short-line-d.svg",
"/img/bg/short-line.svg",
"/img/bg/slanted-lines-d.png",
"/img/bg/slanted-lines.png",
"/img/bg/square-solid-d.svg",
"/img/bg/square-solid.svg",
"/img/bg/star-d.svg",
"/img/bg/star.svg",
"/img/bg/triangle-d.svg",
"/img/bg/triangle.svg",
"/img/bg/wood-d.png",
"/img/bg/wood.png",
"/img/bitcoin.png",
"/img/example.png",
"/img/example.svg",
"/img/github-banner-settings.png",
"/img/github-banner-settings.svg",
"/img/header-banner.png",
"/img/header-banner.svg",
"/img/logo-gray.png",
"/img/logo.png",
"/img/logo.svg",
"/img/maskable_logo_gray.png",
"/img/maskable_logo.png",
"/img/picture2.png",
"/img/picture.png",
"/img/repository-open-graph-template.png",
"/img/screenshot.png",
"/img/tpl/ava.png",
"/img/tpl/",
"/img/tpl/ava.svg",
"/img/tpl/bg-dark.png",
"/img/tpl/bg-dark.svg",
"/img/tpl/bg-light.png",
"/img/tpl/bg.svg",
"/img/tpl/favicon.ico",
"/img/tpl/favicon.png",
"/img/tpl/flower.png",
"/img/tpl/flower.svg",
"/img/tpl/header-banner.svg",
"/img/tpl/image.png",
"/img/tpl/logo2.png",
"/img/tpl/logo2.svg",
"/img/tpl/logo.png",
"/img/tpl/logo.svg",
"/img/tpl/tree.svg",
"/img/tpl/woman.png",
"/img/tpl/woman.svg",
"/img/transparent.png",
"/img/transparent.svg",
"/index.html",
"/js/ads.js",
"/js/",
"/js/cookie-agree-popup.js",
"/js/fu-post-time.js",
"/js/fu-symbol-counter.js",
"/js/main (copy 1).js",
"/js/main.js",
"/js/script-backup.js",
"/js/script (copy 1).js",
"/js/script.js",
"/js/settings-options.js",
"/js/theme-options.js",
"/LICENSE.md",
"/manifest.webmanifest",
"/mini-projects/animated-borders-button-link-5/index.html",
"/mini-projects/",
"/mini-projects/animated-borders-button-link-5/",
"/mini-projects/animated-borders-button-link-5/style.css",
"/mini-projects/animation-test-6/index.html",
"/mini-projects/animation-test-6/",
"/mini-projects/animation-test-6/style.css",
"/mini-projects/background-with-linear-gradient-css-7/index.html",
"/mini-projects/background-with-linear-gradient-css-7/",
"/mini-projects/background-with-linear-gradient-css-7/style.css",
"/mini-projects/button-blur-unblur-28/index.html",
"/mini-projects/button-blur-unblur-28/",
"/mini-projects/button-blur-unblur-28/style.css",
"/mini-projects/empty-page-39/index.html",
"/mini-projects/empty-page-39/",
"/mini-projects/empty-page-39/style.css",
"/mini-projects/flex-grid-32/index.html",
"/mini-projects/flex-grid-32/",
"/mini-projects/flex-grid-32/style.css",
"/mini-projects/heading-33/index.html",
"/mini-projects/heading-33/",
"/mini-projects/heading-33/style.css",
"/mini-projects/hide-show-on-resize-35/index.html",
"/mini-projects/hide-show-on-resize-35/",
"/mini-projects/hide-show-on-resize-35/style.css",
"/mini-projects/html-symbols-36/index.html",
"/mini-projects/html-symbols-36/",
"/mini-projects/html-symbols-36/style.css",
"/mini-projects/index.html",
"/mini-projects/light-and-dark-design-29/index.html",
"/mini-projects/light-and-dark-design-29/",
"/mini-projects/light-and-dark-design-29/style.css",
"/mini-projects/palette-generator-using-css-34/index.html",
"/mini-projects/palette-generator-using-css-34/",
"/mini-projects/palette-generator-using-css-34/style.css",
"/mini-projects/project-ideas-37/index.html",
"/mini-projects/project-ideas-37/",
"/mini-projects/project-ideas-37/style.css",
"/mini-projects/responsive-web-design-2/index.html",
"/mini-projects/responsive-web-design-2/",
"/mini-projects/responsive-web-design-2/script.js",
"/mini-projects/responsive-web-design-2/style.css",
"/mini-projects/simple-page-38/index.html",
"/mini-projects/simple-page-38/",
"/mini-projects/simple-page-38/style.css",
"/mini-projects/sun-and-moon-css-31/index.html",
"/mini-projects/sun-and-moon-css-31/",
"/mini-projects/sun-and-moon-css-31/style.css",
"/mini-projects/tpl-project-mini-1/index.html",
"/mini-projects/tpl-project-mini-1/",
"/mini-projects/tpl-project-mini-1/style.css",
"/old-projects/blocked-65/index.html",
"/old-projects/",
"/old-projects/blocked-65/",
"/old-projects/blocked-65/script.js",
"/old-projects/blocked-65/style.css",
"/old-projects/exit-80/index.html",
"/old-projects/exit-80/",
"/old-projects/exit-80/script.js",
"/old-projects/exit-80/style.css",
"/old-projects/google-trends-46/index.html",
"/old-projects/google-trends-46/",
"/old-projects/google-trends-46/script.js",
"/old-projects/google-trends-46/style.css",
"/old-projects/hello-world-62/index.html",
"/old-projects/hello-world-62/",
"/old-projects/hello-world-62/script.js",
"/old-projects/hello-world-62/style.css",
"/old-projects/index.html",
"/old-projects/not-sleep-pc-12/index.html",
"/old-projects/not-sleep-pc-12/",
"/old-projects/not-sleep-pc-12/style.css",
"/old-projects/pwa-test-21/index.html",
"/old-projects/pwa-test-21/",
"/old-projects/pwa-test-21/manifest.webmanifest",
"/old-projects/pwa-test-21/script.js",
"/old-projects/pwa-test-21/style.css",
"/old-projects/pwa-test-21/sw.js",
"/old-projects/scrolling-76/image.png",
"/old-projects/scrolling-76/",
"/old-projects/scrolling-76/index.html",
"/old-projects/scrolling-76/script.js",
"/old-projects/scrolling-76/style.css",
"/old-projects/textarea-24/index.html",
"/old-projects/textarea-24/",
"/old-projects/textarea-24/style.css",
"/pages/about/index.html",
"/pages/",
"/pages/about/",
"/pages/ads/index.html",
"/pages/ads/",
"/pages/art/2024/acrylic-gimp-12.jpg",
"/pages/art/",
"/pages/art/2024/",
"/pages/art/2024/autumn-forest-pixels-gimp-15.jpg",
"/pages/art/2024/car-technology-gimp-6.jpg",
"/pages/art/2024/cloud-gimp-7.jpg",
"/pages/art/2024/empty-drawing-1.png",
"/pages/art/2024/face-gimp-10.jpg",
"/pages/art/2024/fractal-gimp-17.jpg",
"/pages/art/2024/https-paint-toys-calligram-screenshot-2.png",
"/pages/art/2024/https-paint-toys-mondrian-screenshot-3.png",
"/pages/art/2024/https-paint-toys-oil-screenshot-4.png",
"/pages/art/2024/https-paint-toys-one-line-screenshot-5.jpeg",
"/pages/art/2024/human-cartoon-pixels-gimp-24.png",
"/pages/art/2024/human-waterpixels-pixels-gimp-23.png",
"/pages/art/2024/lines-pixels-gimp-8.jpg",
"/pages/art/2024/night-pixels-gimp-9.jpg",
"/pages/art/2024/owl-bird-gimp-21.png",
"/pages/art/2024/palent-space-pixels-gimp-20.png",
"/pages/art/2024/sky-gimp-16.jpg",
"/pages/art/2024/update-lemon-pixels-gimp-11.jpg",
"/pages/art/2024/water-lake-gimp-22.png",
"/pages/art/2024/wind-gimp-18.jpg",
"/pages/art/2024/winter-pixels-gimp-19.png",
"/pages/art/2025/landscape-gimp-25.png",
"/pages/art/2025/",
"/pages/art/2025/mountains-krita-27.png",
"/pages/art/2025/tool-test-inkscape-26.jpeg",
"/pages/art/index.html",
"/pages/art/tpl-gimp-0.png",
"/pages/blog/index.html",
"/pages/blog/",
"/pages/chrome-extensions/index.html",
"/pages/chrome-extensions/",
"/pages/chrome-extensions/new-tab-redirect-3/a-backup-old.css",
"/pages/chrome-extensions/new-tab-redirect-3/",
"/pages/chrome-extensions/new-tab-redirect-3/auto.css",
"/pages/chrome-extensions/new-tab-redirect-3/icon512x512.png",
"/pages/chrome-extensions/new-tab-redirect-3/icon512x512.svg",
"/pages/chrome-extensions/new-tab-redirect-3/light.css",
"/pages/chrome-extensions/new-tab-redirect-3/main.css",
"/pages/chrome-extensions/new-tab-redirect-3/manifest.json",
"/pages/chrome-extensions/new-tab-redirect-3/new-tab-redirect.html",
"/pages/chrome-extensions/new-tab-redirect-3/options.html",
"/pages/chrome-extensions/new-tab-redirect-3/options.js",
"/pages/chrome-extensions/new-tab-redirect-3/README.md",
"/pages/chrome-extensions/new-tab-redirect-3/screenshot2.png",
"/pages/chrome-extensions/new-tab-redirect-3/screenshot.png",
"/pages/chrome-extensions/new-tab-redirect-3/script.js",
"/pages/chrome-extensions/new-tab-redirect-3/style.css",
"/pages/chrome-extensions/new-tab-redirect-3.crx",
"/pages/chrome-extensions/old/badge-count-up-timer-4/auto.css",
"/pages/chrome-extensions/old/",
"/pages/chrome-extensions/old/badge-count-up-timer-4/",
"/pages/chrome-extensions/old/badge-count-up-timer-4/background.js",
"/pages/chrome-extensions/old/badge-count-up-timer-4/icon512x512.png",
"/pages/chrome-extensions/old/badge-count-up-timer-4/icon512x512.svg",
"/pages/chrome-extensions/old/badge-count-up-timer-4/main.css",
"/pages/chrome-extensions/old/badge-count-up-timer-4/manifest.json",
"/pages/chrome-extensions/old/badge-count-up-timer-4/popup.html",
"/pages/chrome-extensions/old/badge-count-up-timer-4/script.js",
"/pages/chrome-extensions/old/badge-count-up-timer-4/style.css",
"/pages/chrome-extensions/old/badge-count-up-timer-4.crx",
"/pages/chrome-extensions/old/hotkey-url-5/a-backup-old.css",
"/pages/chrome-extensions/old/hotkey-url-5/",
"/pages/chrome-extensions/old/hotkey-url-5/auto.css",
"/pages/chrome-extensions/old/hotkey-url-5/icon512x512.png",
"/pages/chrome-extensions/old/hotkey-url-5/icon512x512.svg",
"/pages/chrome-extensions/old/hotkey-url-5/main.css",
"/pages/chrome-extensions/old/hotkey-url-5/manifest.json",
"/pages/chrome-extensions/old/hotkey-url-5/options.html",
"/pages/chrome-extensions/old/hotkey-url-5/options.js",
"/pages/chrome-extensions/old/hotkey-url-5/README.md",
"/pages/chrome-extensions/old/hotkey-url-5/screenshot.png",
"/pages/chrome-extensions/old/hotkey-url-5/script.js",
"/pages/chrome-extensions/old/hotkey-url-5/style.css",
"/pages/chrome-extensions/old/hotkey-url-5/style-main.css",
"/pages/chrome-extensions/old/hotkey-url-5/worker.js",
"/pages/chrome-extensions/old/hotkey-url-5.crx",
"/pages/chrome-extensions/old/stop-loading-website-7/auto.css",
"/pages/chrome-extensions/old/stop-loading-website-7/",
"/pages/chrome-extensions/old/stop-loading-website-7/icon512x512.png",
"/pages/chrome-extensions/old/stop-loading-website-7/icon512x512.svg",
"/pages/chrome-extensions/old/stop-loading-website-7/main.css",
"/pages/chrome-extensions/old/stop-loading-website-7/manifest.json",
"/pages/chrome-extensions/old/stop-loading-website-7/options.html",
"/pages/chrome-extensions/old/stop-loading-website-7/options.js",
"/pages/chrome-extensions/old/stop-loading-website-7/README.md",
"/pages/chrome-extensions/old/stop-loading-website-7/screenshot.png",
"/pages/chrome-extensions/old/stop-loading-website-7/script.js",
"/pages/chrome-extensions/old/stop-loading-website-7/style.css",
"/pages/chrome-extensions/old/url-redirect-6/auto.css",
"/pages/chrome-extensions/old/url-redirect-6/",
"/pages/chrome-extensions/old/url-redirect-6/icon512x512.png",
"/pages/chrome-extensions/old/url-redirect-6/icon512x512.svg",
"/pages/chrome-extensions/old/url-redirect-6/main.css",
"/pages/chrome-extensions/old/url-redirect-6/manifest.json",
"/pages/chrome-extensions/old/url-redirect-6/options.html",
"/pages/chrome-extensions/old/url-redirect-6/options.js",
"/pages/chrome-extensions/old/url-redirect-6/README.md",
"/pages/chrome-extensions/old/url-redirect-6/screenshot.png",
"/pages/chrome-extensions/old/url-redirect-6/script.js",
"/pages/chrome-extensions/old/url-redirect-6/style.css",
"/pages/chrome-extensions/old/url-redirect-6/url-redirect-6.zip",
"/pages/chrome-extensions/old/url-redirect-6.crx",
"/pages/chrome-extensions/README.md",
"/pages/chrome-themes/dark-theme/manifest.json",
"/pages/chrome-themes/",
"/pages/chrome-themes/dark-theme/",
"/pages/chrome-themes/dark-theme.crx",
"/pages/chrome-themes/dark-theme-screenshot.png",
"/pages/chrome-themes/index.html",
"/pages/chrome-themes/light-theme/manifest.json",
"/pages/chrome-themes/light-theme/",
"/pages/chrome-themes/light-theme.crx",
"/pages/chrome-themes/light-theme-screenshot.png",
"/pages/chrome-themes/Source.txt",
"/pages/chrome-themes/tpl-theme/manifest.json",
"/pages/chrome-themes/tpl-theme/",
"/pages/css-art/city-34/index.html",
"/pages/css-art/",
"/pages/css-art/city-34/",
"/pages/css-art/city-34/style.css",
"/pages/css-art/computer-css-9/index.html",
"/pages/css-art/computer-css-9/",
"/pages/css-art/computer-css-9/style.css",
"/pages/css-art/flower-33/index.html",
"/pages/css-art/flower-33/",
"/pages/css-art/flower-33/style.css",
"/pages/css-art/halloween-pumpkin-css-15/index.html",
"/pages/css-art/halloween-pumpkin-css-15/",
"/pages/css-art/halloween-pumpkin-css-15/style.css",
"/pages/css-art/index.html",
"/pages/css-art/realistic-old-windows-os-popup-window-12/index.html",
"/pages/css-art/realistic-old-windows-os-popup-window-12/",
"/pages/css-art/realistic-old-windows-os-popup-window-12/style.css",
"/pages/css-art/style.css",
"/pages/css-art/tpl-0/index.html",
"/pages/css-art/tpl-0/",
"/pages/css-art/tpl-0/style.css",
"/pages/css-art/woman-css-32/index.html",
"/pages/css-art/woman-css-32/",
"/pages/css-art/woman-css-32/style.css",
"/pages/data-page/index.html",
"/pages/data-page/",
"/pages/firefox-extensions/auto-theme-switcher-8/auto.css",
"/pages/firefox-extensions/",
"/pages/firefox-extensions/auto-theme-switcher-8/",
"/pages/firefox-extensions/auto-theme-switcher-8/auto-theme-switcher-8.zip",
"/pages/firefox-extensions/auto-theme-switcher-8/icon512x512.png",
"/pages/firefox-extensions/auto-theme-switcher-8/icon512x512.svg",
"/pages/firefox-extensions/auto-theme-switcher-8/main.css",
"/pages/firefox-extensions/auto-theme-switcher-8/manifest.json",
"/pages/firefox-extensions/auto-theme-switcher-8/options.html",
"/pages/firefox-extensions/auto-theme-switcher-8/README.md",
"/pages/firefox-extensions/auto-theme-switcher-8/screenshot.png",
"/pages/firefox-extensions/auto-theme-switcher-8/script.js",
"/pages/firefox-extensions/auto-theme-switcher-8/style.css",
"/pages/firefox-extensions/auto-theme-switcher-8/worker.js",
"/pages/firefox-extensions/google-search-unofficial-9/google-search-unofficial-9.zip",
"/pages/firefox-extensions/google-search-unofficial-9/",
"/pages/firefox-extensions/google-search-unofficial-9/icon512x512.png",
"/pages/firefox-extensions/google-search-unofficial-9/icon512x512.svg",
"/pages/firefox-extensions/google-search-unofficial-9/manifest.json",
"/pages/firefox-extensions/google-search-unofficial-9/screenshot.png",
"/pages/firefox-extensions/index.html",
"/pages/firefox-extensions/irvirty-search-redirect-10/icon512x512.png",
"/pages/firefox-extensions/irvirty-search-redirect-10/",
"/pages/firefox-extensions/irvirty-search-redirect-10/icon512x512.svg",
"/pages/firefox-extensions/irvirty-search-redirect-10/irvirty-search-redirect-10.zip",
"/pages/firefox-extensions/irvirty-search-redirect-10/manifest.json",
"/pages/firefox-extensions/irvirty-search-redirect-10/README.md",
"/pages/firefox-extensions/irvirty-search-redirect-10/screenshot.png",
"/pages/firefox-extensions/new-tab-redirect-3/auto.css",
"/pages/firefox-extensions/new-tab-redirect-3/",
"/pages/firefox-extensions/new-tab-redirect-3/icon512x512.png",
"/pages/firefox-extensions/new-tab-redirect-3/icon512x512.svg",
"/pages/firefox-extensions/new-tab-redirect-3/main.css",
"/pages/firefox-extensions/new-tab-redirect-3/manifest.json",
"/pages/firefox-extensions/new-tab-redirect-3/new-tab-redirect-3.zip",
"/pages/firefox-extensions/new-tab-redirect-3/new-tab-redirect.html",
"/pages/firefox-extensions/new-tab-redirect-3/options.html",
"/pages/firefox-extensions/new-tab-redirect-3/options.js",
"/pages/firefox-extensions/new-tab-redirect-3/README.md",
"/pages/firefox-extensions/new-tab-redirect-3/screenshot2.png",
"/pages/firefox-extensions/new-tab-redirect-3/screenshot.png",
"/pages/firefox-extensions/new-tab-redirect-3/script.js",
"/pages/firefox-extensions/new-tab-redirect-3/style.css",
"/pages/firefox-extensions/old/badge-count-up-timer-4/auto.css",
"/pages/firefox-extensions/old/",
"/pages/firefox-extensions/old/badge-count-up-timer-4/",
"/pages/firefox-extensions/old/badge-count-up-timer-4/background.html",
"/pages/firefox-extensions/old/badge-count-up-timer-4/background.js",
"/pages/firefox-extensions/old/badge-count-up-timer-4/badge-count-up-timer-4.zip",
"/pages/firefox-extensions/old/badge-count-up-timer-4/icon512x512.png",
"/pages/firefox-extensions/old/badge-count-up-timer-4/icon512x512.svg",
"/pages/firefox-extensions/old/badge-count-up-timer-4/main.css",
"/pages/firefox-extensions/old/badge-count-up-timer-4/manifest.json",
"/pages/firefox-extensions/old/badge-count-up-timer-4/popup.html",
"/pages/firefox-extensions/old/badge-count-up-timer-4/README.md",
"/pages/firefox-extensions/old/badge-count-up-timer-4/screenshot.png",
"/pages/firefox-extensions/old/badge-count-up-timer-4/script.js",
"/pages/firefox-extensions/old/badge-count-up-timer-4/style.css",
"/pages/firefox-extensions/old/hotkey-url-5/hotkey-url-5.zip",
"/pages/firefox-extensions/old/hotkey-url-5/",
"/pages/firefox-extensions/old/hotkey-url-5/icon512x512.png",
"/pages/firefox-extensions/old/hotkey-url-5/icon512x512.svg",
"/pages/firefox-extensions/old/hotkey-url-5/main.css",
"/pages/firefox-extensions/old/hotkey-url-5/manifest.json",
"/pages/firefox-extensions/old/hotkey-url-5/options.html",
"/pages/firefox-extensions/old/hotkey-url-5/options.js",
"/pages/firefox-extensions/old/hotkey-url-5/README.md",
"/pages/firefox-extensions/old/hotkey-url-5/screenshot.png",
"/pages/firefox-extensions/old/hotkey-url-5/script.js",
"/pages/firefox-extensions/old/hotkey-url-5/style.css",
"/pages/firefox-extensions/old/hotkey-url-5/worker.js",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/auto.css",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/background.js",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/icon-2-512x512.png",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/icon-512x512.png",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/icon-512x512.svg",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/main.css",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/manifest.json",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/options.html",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/popup.html",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/README.md",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/screenshot.png",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/script.js",
"/pages/firefox-extensions/old/rss-button-status-in-progress-9/style.css",
"/pages/firefox-extensions/old/stop-loading-website-7/auto.css",
"/pages/firefox-extensions/old/stop-loading-website-7/",
"/pages/firefox-extensions/old/stop-loading-website-7/icon512x512.png",
"/pages/firefox-extensions/old/stop-loading-website-7/icon512x512.svg",
"/pages/firefox-extensions/old/stop-loading-website-7/main.css",
"/pages/firefox-extensions/old/stop-loading-website-7/manifest.json",
"/pages/firefox-extensions/old/stop-loading-website-7/options.html",
"/pages/firefox-extensions/old/stop-loading-website-7/options.js",
"/pages/firefox-extensions/old/stop-loading-website-7/README.md",
"/pages/firefox-extensions/old/stop-loading-website-7/screenshot.png",
"/pages/firefox-extensions/old/stop-loading-website-7/script.js",
"/pages/firefox-extensions/old/stop-loading-website-7/stop-loading-website-7.zip",
"/pages/firefox-extensions/old/stop-loading-website-7/style.css",
"/pages/firefox-extensions/old/url-redirect-6/auto.css",
"/pages/firefox-extensions/old/url-redirect-6/",
"/pages/firefox-extensions/old/url-redirect-6/icon512x512.png",
"/pages/firefox-extensions/old/url-redirect-6/icon512x512.svg",
"/pages/firefox-extensions/old/url-redirect-6/main.css",
"/pages/firefox-extensions/old/url-redirect-6/manifest.json",
"/pages/firefox-extensions/old/url-redirect-6/options.html",
"/pages/firefox-extensions/old/url-redirect-6/options.js",
"/pages/firefox-extensions/old/url-redirect-6/README.md",
"/pages/firefox-extensions/old/url-redirect-6/screenshot.png",
"/pages/firefox-extensions/old/url-redirect-6/script (copy 1).js",
"/pages/firefox-extensions/old/url-redirect-6/script.js",
"/pages/firefox-extensions/old/url-redirect-6/style.css",
"/pages/firefox-extensions/old/url-redirect-6/url-redirect-6.zip",
"/pages/firefox-extensions/search-localhost-http-1/icon512x512.png",
"/pages/firefox-extensions/search-localhost-http-1/",
"/pages/firefox-extensions/search-localhost-http-1/icon512x512.svg",
"/pages/firefox-extensions/search-localhost-http-1/manifest.json",
"/pages/firefox-extensions/search-localhost-http-1/screenshot.png",
"/pages/firefox-extensions/search-localhost-http-1/search-localhost-http-1.zip",
"/pages/firefox-extensions/search-localhost-https-2/icon512x512.png",
"/pages/firefox-extensions/search-localhost-https-2/",
"/pages/firefox-extensions/search-localhost-https-2/icon512x512.svg",
"/pages/firefox-extensions/search-localhost-https-2/manifest.json",
"/pages/firefox-extensions/search-localhost-https-2/search-localhost-https-2.zip",
"/pages/firefox-themes/index.html",
"/pages/firefox-themes/",
"/pages/firefox-themes/README.md",
"/pages/firefox-themes/screenshot2.png",
"/pages/firefox-themes/screenshot.png",
"/pages/firefox-themes/simple-dark-flat-theme.zip",
"/pages/firefox-themes/simple-light-flat-theme.zip",
"/pages/geany-themes/abc-dark.conf",
"/pages/geany-themes/",
"/pages/geany-themes/abc-dark.png",
"/pages/geany-themes/abc-light.conf",
"/pages/geany-themes/abc-light.png",
"/pages/geany-themes/dark.css",
"/pages/geany-themes/index.html",
"/pages/geany-themes/light.css",
"/pages/geany-themes/README.md",
"/pages/guestbook/index.html",
"/pages/guestbook/",
"/pages/guestbook/style.css",
"/pages/icons/agree.svg",
"/pages/icons/",
"/pages/icons/app.svg",
"/pages/icons/blocked.svg",
"/pages/icons/books.svg",
"/pages/icons/bottom-line.svg",
"/pages/icons/button.svg",
"/pages/icons/calculator.svg",
"/pages/icons/camera.svg",
"/pages/icons/chart.svg",
"/pages/icons/circle.svg",
"/pages/icons/clapper-board.svg",
"/pages/icons/clock.svg",
"/pages/icons/close.svg",
"/pages/icons/code.svg",
"/pages/icons/dot.svg",
"/pages/icons/down-arrow.svg",
"/pages/icons/droplet.svg",
"/pages/icons/filter.svg",
"/pages/icons/folder.svg",
"/pages/icons/four-rectangles.svg",
"/pages/icons/game.svg",
"/pages/icons/gear.svg",
"/pages/icons/grid.svg",
"/pages/icons/heart.svg",
"/pages/icons/herb.svg",
"/pages/icons/hi.svg",
"/pages/icons/home.svg",
"/pages/icons/h.svg",
"/pages/icons/icons-data.zip",
"/pages/icons/image.svg",
"/pages/icons/index.html",
"/pages/icons/information.svg",
"/pages/icons/inspiration-log.html",
"/pages/icons/keyboard.svg",
"/pages/icons/left-arrow.svg",
"/pages/icons/light-bulb.svg",
"/pages/icons/link.svg",
"/pages/icons/list.svg",
"/pages/icons/live.svg",
"/pages/icons/memo.svg",
"/pages/icons/menu-open.svg",
"/pages/icons/menu.svg",
"/pages/icons/movie.svg",
"/pages/icons/music.svg",
"/pages/icons/navigation.svg",
"/pages/icons/newspaper.svg",
"/pages/icons/new.svg",
"/pages/icons/number.svg",
"/pages/icons/page.svg",
"/pages/icons/palette.svg",
"/pages/icons/paste.svg",
"/pages/icons/pencil.svg",
"/pages/icons/play.svg",
"/pages/icons/plus.svg",
"/pages/icons/printer.svg",
"/pages/icons/profile.svg",
"/pages/icons/progress.svg",
"/pages/icons/proportions.svg",
"/pages/icons/pushpin.svg",
"/pages/icons/question.svg",
"/pages/icons/radio.svg",
"/pages/icons/redirect-arraw.svg",
"/pages/icons/refresh.svg",
"/pages/icons/resize.svg",
"/pages/icons/right-arrow.svg",
"/pages/icons/rss.svg",
"/pages/icons/search.svg",
"/pages/icons/service.svg",
"/pages/icons/shuffle.svg",
"/pages/icons/sound.svg",
"/pages/icons/square.svg",
"/pages/icons/star.svg",
"/pages/icons/store.svg",
"/pages/icons/textarea.svg",
"/pages/icons/text.svg",
"/pages/icons/three-dots.svg",
"/pages/icons/travel.svg",
"/pages/icons/tv.svg",
"/pages/icons/up-arrow.svg",
"/pages/icons/usb-drive.svg",
"/pages/icons/warning.svg",
"/pages/icons/weather.svg",
"/pages/images/2024/ai-assistant-inkscape-62.png",
"/pages/images/",
"/pages/images/2024/",
"/pages/images/2024/ava-woman-laptop-ava-inkscape-12.svg",
"/pages/images/2024/ava-woman-laptop-inkscape-30.svg",
"/pages/images/2024/barbie-time-inkscape-10.svg",
"/pages/images/2024/bg-black-krita-39.png",
"/pages/images/2024/bg-white-krita-38.png",
"/pages/images/2024/building-krita-1.png",
"/pages/images/2024/day-night-inkscap-56.svg",
"/pages/images/2024/day-night-inkscape-45.png",
"/pages/images/2024/editor-code-light-dark-mode-27.gif",
"/pages/images/2024/html-css-js-javascript-inkscape-72.svg",
"/pages/images/2024/html-css-js-javascript-inkscape-73.png",
"/pages/images/2024/icon-app-64.png",
"/pages/images/2024/landscape-inkscape-2.svg",
"/pages/images/2024/logo-logotype-circle-oval-inkscap-40.svg",
"/pages/images/2024/logo-logotype-circle-oval-inkscape-41.png",
"/pages/images/2024/logo-logotype-css-inkscape-66.svg",
"/pages/images/2024/logo-logotype-css-inkscape-67.png",
"/pages/images/2024/logo-logotype-diamond-inkscape-34.png",
"/pages/images/2024/logo-logotype-html-inkscape-68.svg",
"/pages/images/2024/logo-logotype-html-inkscape-69.png",
"/pages/images/2024/logo-logotype-js-inkscape-70.svg",
"/pages/images/2024/logo-logotype-js-inkscape-71.png",
"/pages/images/2024/logo-logotype-t-inkscape-6.svg",
"/pages/images/2024/logo-logotype-x-inkscape-5.svg",
"/pages/images/2024/logo-logotype-x-inkscape-7.svg",
"/pages/images/2024/logo-logotype-x-inkscape-8.svg",
"/pages/images/2024/logo-logotype-x-inkscape-9.svg",
"/pages/images/2024/mail-art-inkscape-31.svg",
"/pages/images/2024/music-note-icon-inkscape-44.svg",
"/pages/images/2024/one-black-pixel-inkscape-35.png",
"/pages/images/2024/one-transparent-pixel-inkscape-37.png",
"/pages/images/2024/one-white-pixel-inkscape-36.png",
"/pages/images/2024/rss-icon-63.png",
"/pages/images/2024/search-page-inkscape-61.png",
"/pages/images/2024/sound-ico-65.png",
"/pages/images/2024/star-inkscape-4.svg",
"/pages/images/2024/start-end-krita-0.png",
"/pages/images/2024/test-inkscape-57.svg",
"/pages/images/2024/test-inkscape-58.png",
"/pages/images/2024/transparent-background-inkscape-29.png",
"/pages/images/2024/wallpaper-desktop-binary-text-dark-inkscape-26.png",
"/pages/images/2024/wallpaper-desktop-binary-text-light-inkscape-25.png",
"/pages/images/2024/wallpaper-desktop-circle-dark-16.jpg",
"/pages/images/2024/wallpaper-desktop-circle-light-15.jpg",
"/pages/images/2024/wallpaper-desktop-circle-olive-14.jpg",
"/pages/images/2024/wallpaper-desktop-hello-world-big-black-inkscape-55.png",
"/pages/images/2024/wallpaper-desktop-hello-world-big-dark-inkscape-50.svg",
"/pages/images/2024/wallpaper-desktop-hello-world-big-dark-inkscape-51.png",
"/pages/images/2024/wallpaper-desktop-hello-world-big-light-inkscape-52.svg",
"/pages/images/2024/wallpaper-desktop-hello-world-big-light-inkscape-53.png",
"/pages/images/2024/wallpaper-desktop-hello-world-big-white-inkscape-54.png",
"/pages/images/2024/wallpaper-desktop-hello-world-binary-black-inkscape-48.png",
"/pages/images/2024/wallpaper-desktop-hello-world-binary-dark-inkscape-46.svg",
"/pages/images/2024/wallpaper-desktop-hello-world-binary-light-inkscape-47.svg",
"/pages/images/2024/wallpaper-desktop-hello-world-binary-text-dark-inkscape-42.png",
"/pages/images/2024/wallpaper-desktop-hello-world-binary-text-light-inkscape-43.png",
"/pages/images/2024/wallpaper-desktop-hello-world-binary-white-inkscape-49.png",
"/pages/images/2024/wallpaper-desktop-landscape-dark-blue-inkscape-20.jpg",
"/pages/images/2024/wallpaper-desktop-landscape-light-blue-inkscape-19.jpg",
"/pages/images/2024/wallpaper-desktop-triangle-dark-17.jpg",
"/pages/images/2024/wallpaper-desktop-triangle-light-18.jpg",
"/pages/images/2024/wallpaper-mobile-binary-text-dark-inkscape-23.png",
"/pages/images/2024/wallpaper-mobile-binary-text-light-inkscape-24.png",
"/pages/images/2024/wallpaper-mobile-landscape-dark-blue-inkscape-21.jpg",
"/pages/images/2024/wallpaper-mobile-landscape-light-blue-inkscape-22.jpg",
"/pages/images/2024/web-design-trend-svg-inkscap-11.svg",
"/pages/images/2024/website-inkscape-59.svg",
"/pages/images/2024/website-inkscape-60.png",
"/pages/images/2025/logo-logotype-latter-i-inkscape-98.svg",
"/pages/images/2025/",
"/pages/images/2025/logo-logotype-latter-i-inkscape-99.png",
"/pages/images/2025/logo-logotype-template-letter-t-inkscape-106.svg",
"/pages/images/2025/wallpaper-desktop-abstract-paper-ligh-gimp-inkscape-75.jpeg",
"/pages/images/2025/wallpaper-desktop-art-abstract-grunge-dark-gimp-90.jpeg",
"/pages/images/2025/wallpaper-desktop-art-abstract-grunge-light-gimp-89.jpeg",
"/pages/images/2025/wallpaper-desktop-art-abstract-shapes-cubism-grunge-light-gimp-88.jpeg",
"/pages/images/2025/wallpaper-desktop-clean-lines-dark-inkscape-95.png",
"/pages/images/2025/wallpaper-desktop-clean-lines-light-blue-inkscape-97.png",
"/pages/images/2025/wallpaper-desktop-clean-lines-light-inkscape-93.svg",
"/pages/images/2025/wallpaper-desktop-clean-lines-light-inkscape-94.png",
"/pages/images/2025/wallpaper-desktop-illusion-plasma-gimp-87.jpeg",
"/pages/images/2025/wallpaper-desktop-numbers-js-css-gimp-85.jpeg",
"/pages/images/2025/wallpaper-desktop-rectangles-dark-inkscape-81.png",
"/pages/images/2025/wallpaper-desktop-shapes-inkscape-76.svg",
"/pages/images/2025/wallpaper-desktop-shapes-inkscape-gimp-77.png",
"/pages/images/2025/wallpaper-desktop-tile-kaleidoscope-mandala-dark-gimp-92.jpeg",
"/pages/images/2025/wallpaper-desktop-tile-kaleidoscope-mandala-light-gimp-91.jpeg",
"/pages/images/2025/wallpaper-desktop-wall-inkscape-gimp-78.jpeg",
"/pages/images/2025/wallpaper-desktop-wall-rectangles-light-inkscape-102.png",
"/pages/images/2025/wallpaper-desktop-wall-rectangles-light-inkscape-103.svg",
"/pages/images/2025/wallpaper-desktop-waves-dark-inkscape-84.png",
"/pages/images/2025/wallpaper-desktop-waves-light-inkscape-82.svg",
"/pages/images/2025/wallpaper-desktop-waves-light-inkscape-83.png",
"/pages/images/2025/wallpaper-desktop-waves-light-silver-inkscape-86.png",
"/pages/images/2025/wallpaper-desktop-waves-lines-dark-inkscape-104.svg",
"/pages/images/2025/wallpaper-desktop-waves-lines-dark-inkscape-105.png",
"/pages/images/2025/wallpaper-desktop-waves-lines-light-blue-inkscape-96.png",
"/pages/images/2025/wallpaper-desktop-waves-lines-light-inkscape-100.svg",
"/pages/images/2025/wallpaper-desktop-waves-lines-light-inkscape-101.png",
"/pages/images/index.html",
"/pages/index.html",
"/pages/install/index.html",
"/pages/install/",
"/pages/links/index.html",
"/pages/links/",
"/pages/microblog/index.html",
"/pages/microblog/",
"/pages/microblog/style.css",
"/pages/news/index.html",
"/pages/news/",
"/pages/notes/index.html",
"/pages/notes/",
"/pages/services/index.html",
"/pages/services/",
"/pages/settings/index.html",
"/pages/settings/",
"/pages/sitemap/index.html",
"/pages/sitemap/",
"/pages/themes/index.html",
"/pages/themes/",
"/pages/updates/index.html",
"/pages/updates/",
"/pages/website-templates/about-me-page-auto-light-dark-21/index.html",
"/pages/website-templates/",
"/pages/website-templates/about-me-page-auto-light-dark-21/",
"/pages/website-templates/about-me-page-auto-light-dark-21/style.css",
"/pages/website-templates/about-underline-why-underline-important-auto-light-dark-26/index.html",
"/pages/website-templates/about-underline-why-underline-important-auto-light-dark-26/",
"/pages/website-templates/about-underline-why-underline-important-auto-light-dark-26/style.css",
"/pages/website-templates/card-page-auto-light-dark-20/image.png",
"/pages/website-templates/card-page-auto-light-dark-20/",
"/pages/website-templates/card-page-auto-light-dark-20/index.html",
"/pages/website-templates/card-page-auto-light-dark-20/page.html",
"/pages/website-templates/card-page-auto-light-dark-20/style.css",
"/pages/website-templates/clean-one-page-mini-simple-auto-light-dark-16/index.html",
"/pages/website-templates/clean-one-page-mini-simple-auto-light-dark-16/",
"/pages/website-templates/clean-one-page-mini-simple-auto-light-dark-16/style.css",
"/pages/website-templates/clean-simple-micro-auto-light-dark-24/index.html",
"/pages/website-templates/clean-simple-micro-auto-light-dark-24/",
"/pages/website-templates/clean-simple-micro-auto-light-dark-24/style.css",
"/pages/website-templates/flower-one-page-mini-flat-auto-light-dark-17/flower.svg",
"/pages/website-templates/flower-one-page-mini-flat-auto-light-dark-17/",
"/pages/website-templates/flower-one-page-mini-flat-auto-light-dark-17/index.html",
"/pages/website-templates/flower-one-page-mini-flat-auto-light-dark-17/style.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/auto.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/dark.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-blue.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-forest.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-green.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-orange.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-pink.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-plum.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-purple.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-red.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-sea.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-slate.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-violet.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/d-yellow.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/empty.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/h-contrast-d.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/h-contrast-l.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/hight-contrast-dark.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/hight-contrast-light.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-blue.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-green.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/light.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-merino.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-olive.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-orange.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-pink.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-plum.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-purple.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-red.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-sea.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-seashell.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-violet.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/l-yellow.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/main (copy 1).css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/main.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/noscript.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-blue.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-blue.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-brown.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-forest.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-gray.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-green.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-olive.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-pink.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-plum.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-purple.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-red.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-sea.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-slate.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-violet.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/od-yellow.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-green.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-lime.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-mint.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-olive.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-orange.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-pink.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-plum.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-purple.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-red.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-sea.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-silver.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-violet.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/o-yellow.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/rss.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/css/style.css",
"/pages/website-templates/homepage-flat-many-colors-themes-10/index.html",
"/pages/website-templates/homepage-flat-many-colors-themes-10/main.js",
"/pages/website-templates/homepage-flat-many-colors-themes-10/menu.html",
"/pages/website-templates/homepage-flat-many-colors-themes-10/page.html",
"/pages/website-templates/homepage-flat-many-colors-themes-10/theme-options.js",
"/pages/website-templates/homepage-flat-many-colors-themes-10/themes.html",
"/pages/website-templates/homepage-flat-mini-auto-light-dark-9/index.html",
"/pages/website-templates/homepage-flat-mini-auto-light-dark-9/",
"/pages/website-templates/homepage-flat-mini-auto-light-dark-9/menu.html",
"/pages/website-templates/homepage-flat-mini-auto-light-dark-9/page.html",
"/pages/website-templates/homepage-flat-mini-auto-light-dark-9/style.css",
"/pages/website-templates/index.html",
"/pages/website-templates/movie-flat-auto-light-dark-11/index.html",
"/pages/website-templates/movie-flat-auto-light-dark-11/",
"/pages/website-templates/movie-flat-auto-light-dark-11/movie-id.html",
"/pages/website-templates/movie-flat-auto-light-dark-11/movie-poster2.png",
"/pages/website-templates/movie-flat-auto-light-dark-11/movie-poster.png",
"/pages/website-templates/movie-flat-auto-light-dark-11/name.html",
"/pages/website-templates/movie-flat-auto-light-dark-11/search.html",
"/pages/website-templates/movie-flat-auto-light-dark-11/style.css",
"/pages/website-templates/personal-2/index.html",
"/pages/website-templates/personal-2/",
"/pages/website-templates/personal-2/style.css",
"/pages/website-templates/personal-3/index.html",
"/pages/website-templates/personal-3/",
"/pages/website-templates/personal-3/style.css",
"/pages/website-templates/photo-gallery-one-page-flat-auto-light-dark-18/index.html",
"/pages/website-templates/photo-gallery-one-page-flat-auto-light-dark-18/",
"/pages/website-templates/photo-gallery-one-page-flat-auto-light-dark-18/style.css",
"/pages/website-templates/profile-card-flat-mini-auto-light-dark-12/index.html",
"/pages/website-templates/profile-card-flat-mini-auto-light-dark-12/",
"/pages/website-templates/profile-card-flat-mini-auto-light-dark-12/style.css",
"/pages/website-templates/profile-card-mini-flat-auto-light-dark-14/index.html",
"/pages/website-templates/profile-card-mini-flat-auto-light-dark-14/",
"/pages/website-templates/profile-card-mini-flat-auto-light-dark-14/style.css",
"/pages/website-templates/saas-landing-page-auto-light-dark-19/index.html",
"/pages/website-templates/saas-landing-page-auto-light-dark-19/",
"/pages/website-templates/saas-landing-page-auto-light-dark-19/login.html",
"/pages/website-templates/saas-landing-page-auto-light-dark-19/product2.png",
"/pages/website-templates/saas-landing-page-auto-light-dark-19/product3.png",
"/pages/website-templates/saas-landing-page-auto-light-dark-19/product4.png",
"/pages/website-templates/saas-landing-page-auto-light-dark-19/product.png",
"/pages/website-templates/saas-landing-page-auto-light-dark-19/style (copy 1).css",
"/pages/website-templates/saas-landing-page-auto-light-dark-19/style.css",
"/pages/website-templates/services-landing-page-auto-light-dark-25/index.html",
"/pages/website-templates/services-landing-page-auto-light-dark-25/",
"/pages/website-templates/services-landing-page-auto-light-dark-25/style.css",
"/pages/website-templates/simple-4/index.html",
"/pages/website-templates/simple-4/",
"/pages/website-templates/simple-4/style.css",
"/pages/website-templates/simple-5/index.html",
"/pages/website-templates/simple-5/",
"/pages/website-templates/simple-5/style.css",
"/pages/website-templates/simple-6/index.html",
"/pages/website-templates/simple-6/",
"/pages/website-templates/simple-6/style.css",
"/pages/website-templates/simple-7/index.html",
"/pages/website-templates/simple-7/",
"/pages/website-templates/simple-7/style.css",
"/pages/website-templates/simple-8/index.html",
"/pages/website-templates/simple-8/",
"/pages/website-templates/simple-8/style.css",
"/pages/website-templates/simple-text-1/index.html",
"/pages/website-templates/simple-text-1/",
"/pages/website-templates/simple-text-1/style.css",
"/pages/website-templates/simple-website-template-27/index.html",
"/pages/website-templates/simple-website-template-27/",
"/pages/website-templates/simple-website-template-27/style.css",
"/pages/website-templates/tpl-0/index.html",
"/pages/website-templates/tpl-0/",
"/pages/website-templates/tpl-0/style.css",
"/pages/website-templates/web-design-one-page-mini-flat-auto-light-dark-15/circle.svg",
"/pages/website-templates/web-design-one-page-mini-flat-auto-light-dark-15/",
"/pages/website-templates/web-design-one-page-mini-flat-auto-light-dark-15/coffee.svg",
"/pages/website-templates/web-design-one-page-mini-flat-auto-light-dark-15/index.html",
"/pages/website-templates/web-design-one-page-mini-flat-auto-light-dark-15/style.css",
"/pages/website-templates/web-design-services-simple-auto-light-dark-22/index.html",
"/pages/website-templates/web-design-services-simple-auto-light-dark-22/",
"/pages/website-templates/web-design-services-simple-auto-light-dark-22/style.css",
"/pages/wiki/index.html",
"/pages/wiki/",
"/pages/wordpress-themes/index.html",
"/pages/wordpress-themes/",
"/pages/wordpress-themes/simplehomepage/LICENSE.md",
"/pages/wordpress-themes/simplehomepage/",
"/pages/wordpress-themes/simplehomepage/README.md",
"/pages/wordpress-themes/simplehomepage/screenshot.png",
"/pages/wordpress-themes/simplehomepage/simplehomepage (copy 1).zip",
"/pages/wordpress-themes/simplehomepage/simplehomepage-old-with-auto-css.zip",
"/pages/wordpress-themes/simplehomepage/simplehomepage.zip",
"/projects/agi-countdown-59/data-list.html",
"/projects/",
"/projects/agi-countdown-59/",
"/projects/agi-countdown-59/index.html",
"/projects/agi-countdown-59/script.js",
"/projects/agi-countdown-59/style.css",
"/projects/average-number-40/index.html",
"/projects/average-number-40/",
"/projects/average-number-40/script.js",
"/projects/average-number-40/style.css",
"/projects/background-colors-list-50/index.html",
"/projects/background-colors-list-50/",
"/projects/background-colors-list-50/script.js",
"/projects/background-colors-list-50/style.css",
"/projects/browser-info-test-js-2/index.html",
"/projects/browser-info-test-js-2/",
"/projects/browser-info-test-js-2/script.js",
"/projects/browser-info-test-js-2/style.css",
"/projects/calculator-3/index.html",
"/projects/calculator-3/",
"/projects/calculator-3/script.js",
"/projects/calculator-3/style.css",
"/projects/color-picker-4/index.html",
"/projects/color-picker-4/",
"/projects/color-picker-4/script.js",
"/projects/color-picker-4/style.css",
"/projects/demo-test-style-class-5/index.html",
"/projects/demo-test-style-class-5/",
"/projects/demo-test-style-class-5/script.js",
"/projects/demo-test-style-class-5/style.css",
"/projects/demo-test-style-ui-60/index.html",
"/projects/demo-test-style-ui-60/",
"/projects/demo-test-style-ui-60/script.js",
"/projects/demo-test-style-ui-60/style.css",
"/projects/disqus-comments-74/index.html",
"/projects/disqus-comments-74/",
"/projects/disqus-comments-74/script.js",
"/projects/disqus-comments-74/style.css",
"/projects/drawing-7/index.html",
"/projects/drawing-7/",
"/projects/drawing-7/script.js",
"/projects/drawing-7/style.css",
"/projects/google-programmable-search-49/clean.html",
"/projects/google-programmable-search-49/",
"/projects/google-programmable-search-49/index.html",
"/projects/google-programmable-search-49/readme.txt",
"/projects/google-programmable-search-49/script.js",
"/projects/google-programmable-search-49/style.css",
"/projects/highlight-word-15/index.html",
"/projects/highlight-word-15/",
"/projects/highlight-word-15/script.js",
"/projects/highlight-word-15/style.css",
"/projects/html-colors-name-73/index.html",
"/projects/html-colors-name-73/",
"/projects/html-colors-name-73/script.js",
"/projects/html-colors-name-73/style.css",
"/projects/index.html",
"/projects/insert-icon-17/demo.js",
"/projects/insert-icon-17/",
"/projects/insert-icon-17/index.html",
"/projects/insert-icon-17/old-emoji-script (copy 1).js",
"/projects/insert-icon-17/old-material-icon-script.js",
"/projects/insert-icon-17/script.js",
"/projects/insert-icon-17/style.css",
"/projects/keep-1/index.html",
"/projects/keep-1/",
"/projects/keep-1/script (copy 1).js",
"/projects/keep-1/script.js",
"/projects/keep-1/style.css",
"/projects/lag-test-47/index.html",
"/projects/lag-test-47/",
"/projects/lag-test-47/script.js",
"/projects/lag-test-47/style.css",
"/projects/movie-list-19/index.html",
"/projects/movie-list-19/",
"/projects/movie-list-19/script.js",
"/projects/movie-list-19/style.css",
"/projects/music-20/data-list.html",
"/projects/music-20/",
"/projects/music-20/index.html",
"/projects/music-20/script.js",
"/projects/music-20/style.css",
"/projects/navigation-menu-71/demo.js",
"/projects/navigation-menu-71/",
"/projects/navigation-menu-71/index.html",
"/projects/navigation-menu-71/noscript.css",
"/projects/navigation-menu-71/README.md",
"/projects/navigation-menu-71/screenshot.png",
"/projects/navigation-menu-71/script (copy 1).js",
"/projects/navigation-menu-71/script (copy 2).js",
"/projects/navigation-menu-71/script.js",
"/projects/navigation-menu-71/style.css",
"/projects/podcast-70/index.html",
"/projects/podcast-70/",
"/projects/podcast-70/script.js",
"/projects/podcast-70/style.css",
"/projects/print-53/index.html",
"/projects/print-53/",
"/projects/print-53/script.js",
"/projects/print-53/style.css",
"/projects/radio-22/index.html",
"/projects/radio-22/",
"/projects/radio-22/script.js",
"/projects/radio-22/style.css",
"/projects/rain-38/index.html",
"/projects/rain-38/",
"/projects/rain-38/script.js",
"/projects/rain-38/style.css",
"/projects/random-color-generator-51/demo.js",
"/projects/random-color-generator-51/",
"/projects/random-color-generator-51/index.html",
"/projects/random-color-generator-51/script.js",
"/projects/random-color-generator-51/style.css",
"/projects/random-symbols-23/index.html",
"/projects/random-symbols-23/",
"/projects/random-symbols-23/script.js",
"/projects/random-symbols-23/style.css",
"/projects/random-text-generator-24/index.html",
"/projects/random-text-generator-24/",
"/projects/random-text-generator-24/script.js",
"/projects/random-text-generator-24/style.css",
"/projects/random-website-69/index.html",
"/projects/random-website-69/",
"/projects/random-website-69/script.js",
"/projects/random-website-69/style.css",
"/projects/random-word-every-day-76/index.html",
"/projects/random-word-every-day-76/",
"/projects/random-word-every-day-76/script.js",
"/projects/random-word-every-day-76/style.css",
"/projects/redirects-25/index.html",
"/projects/redirects-25/",
"/projects/redirects-25/script.js",
"/projects/redirects-25/style.css",
"/projects/remove-duplicates-61/index.html",
"/projects/remove-duplicates-61/",
"/projects/remove-duplicates-61/script.js",
"/projects/remove-duplicates-61/style.css",
"/projects/scroll-effect-when-scroll-48/index.html",
"/projects/scroll-effect-when-scroll-48/",
"/projects/scroll-effect-when-scroll-48/script.js",
"/projects/scroll-effect-when-scroll-48/style.css",
"/projects/sorting-55/index.html",
"/projects/sorting-55/",
"/projects/sorting-55/script.js",
"/projects/sorting-55/style.css",
"/projects/speech-to-text-63/index.html",
"/projects/speech-to-text-63/",
"/projects/speech-to-text-63/script.js",
"/projects/speech-to-text-63/style.css",
"/projects/speed-dial-58/index.html",
"/projects/speed-dial-58/",
"/projects/speed-dial-58/script.js",
"/projects/speed-dial-58/style.css",
"/projects/start-page-41/index.html",
"/projects/start-page-41/",
"/projects/start-page-41/script.js",
"/projects/start-page-41/style.css",
"/projects/symbol-counter-39/index.html",
"/projects/symbol-counter-39/",
"/projects/symbol-counter-39/script.js",
"/projects/symbol-counter-39/style.css",
"/projects/tag-cloud-79/index.html",
"/projects/tag-cloud-79/",
"/projects/tag-cloud-79/script.js",
"/projects/tag-cloud-79/style.css",
"/projects/test-page-27/cursor-hl.png",
"/projects/test-page-27/",
"/projects/test-page-27/cursor-hl.psd",
"/projects/test-page-27/index.html",
"/projects/test-page-27/README.md",
"/projects/test-page-27/screenshot.png",
"/projects/test-page-27/script.js",
"/projects/test-page-27/style.css",
"/projects/text-to-binary-52/index.html",
"/projects/text-to-binary-52/",
"/projects/text-to-binary-52/script.js",
"/projects/text-to-binary-52/style.css",
"/projects/text-to-speech-64/index (copy 1).html",
"/projects/text-to-speech-64/",
"/projects/text-to-speech-64/index.html",
"/projects/text-to-speech-64/script (copy 1).js",
"/projects/text-to-speech-64/script.js",
"/projects/text-to-speech-64/style.css",
"/projects/text-to-url-43/index.html",
"/projects/text-to-url-43/",
"/projects/text-to-url-43/script.js",
"/projects/text-to-url-43/style.css",
"/projects/time-binary-clock-28/index.html",
"/projects/time-binary-clock-28/",
"/projects/time-binary-clock-28/script.js",
"/projects/time-binary-clock-28/style.css",
"/projects/time-clock-29/index.html",
"/projects/time-clock-29/",
"/projects/time-clock-29/script.js",
"/projects/time-clock-29/style.css",
"/projects/time-stopwatch-30/index.html",
"/projects/time-stopwatch-30/",
"/projects/time-stopwatch-30/script.js",
"/projects/time-stopwatch-30/style.css",
"/projects/time-utc-clock-56/index.html",
"/projects/time-utc-clock-56/",
"/projects/time-utc-clock-56/script.js",
"/projects/time-utc-clock-56/style.css",
"/projects/todo-list-31/index.html",
"/projects/todo-list-31/",
"/projects/todo-list-31/script.js",
"/projects/todo-list-31/style.css",
"/projects/todo-list-ideas-32/index.html",
"/projects/todo-list-ideas-32/",
"/projects/todo-list-ideas-32/script.js",
"/projects/todo-list-ideas-32/style.css",
"/projects/tpl-projects-33/index.html",
"/projects/tpl-projects-33/",
"/projects/tpl-projects-33/script.js",
"/projects/tpl-projects-33/style.css",
"/projects/tpl-projects-app-34/index.html",
"/projects/tpl-projects-app-34/",
"/projects/tpl-projects-app-34/manifest.webmanifest",
"/projects/tpl-projects-app-34/README.md",
"/projects/tpl-projects-app-34/screenshot.png",
"/projects/tpl-projects-app-34/script.js",
"/projects/tpl-projects-app-34/style.css",
"/projects/tpl-projects-app-34/sw.js",
"/projects/tv-36/index.html",
"/projects/tv-36/",
"/projects/tv-36/script.js",
"/projects/tv-36/style.css",
"/projects/uk-transliteration-35/index.html",
"/projects/uk-transliteration-35/",
"/projects/uk-transliteration-35/script.js",
"/projects/uk-transliteration-35/style.css",
"/projects/video-18/index.html",
"/projects/video-18/",
"/projects/video-18/script.js",
"/projects/video-18/style.css",
"/projects/virtual-keyboard-72/index.html",
"/projects/virtual-keyboard-72/",
"/projects/virtual-keyboard-72/script.js",
"/projects/virtual-keyboard-72/style.css",
"/projects/virtual-travel-78/countriesJsonVar.js",
"/projects/virtual-travel-78/",
"/projects/virtual-travel-78/index.html",
"/projects/virtual-travel-78/script.js",
"/projects/virtual-travel-78/style.css",
"/projects/weather-37/index.html",
"/projects/weather-37/",
"/projects/weather-37/script.js",
"/projects/weather-37/style.css",
"/projects/website-analysis-75/index.html",
"/projects/website-analysis-75/",
"/projects/website-analysis-75/script.js",
"/projects/website-analysis-75/style.css",
"/projects/website-cost-77/data-list.html",
"/projects/website-cost-77/",
"/projects/website-cost-77/index.html",
"/projects/website-cost-77/script.js",
"/projects/website-cost-77/style.css",
"/README.md",
"/robots.txt",
"/rss2.xml",
"/rss.xml",
"/search/index.html",
"/search/",
"/search/script.js",
"/search/style.css",
"/sitemap.xml",
"/site-search/index.html",
"/site-search/",
"/site-search/style.css",
"/sw.js",
"/video/video.mp4",
"/video/",
"/",];
fileListArr.push("no_exit_file_name_for_test.hmtl");

//https://stackoverflow.com/questions/9229645/remove-duplicate-values-from-js-array
fileListArr = [...new Set(fileListArr)]; 




fileListArr.forEach((file) => {
//https://stackoverflow.com/questions/68595209/js-fetch-check-if-file-present-without-downloading-content

//file = '/' + file;

//rm ext
var newFile = hideLinkExt(file);



// with ext
fetch(
file, { method: "HEAD" }
)
.then((res) => {
if (res.ok) {
// file is present at URL
console.log('try cache.add ' + file);
//https://web.dev/learn/pwa/caching/
caches.open("v.1.2.2025.10")
.then(cache => {
cache.add(file); // it stores only one resource
//  cache.addAll(["styles.css", "app.js"]); // it stores two resources
});
} else {
console.log('404 not found ' + file);
// file is not present at URL
}
})
.catch((error) => {
  console.log(error)
});


if(file != newFile){

// no ext
fetch(
newFile, { method: "HEAD" }
)
.then((res) => {
if (res.ok) {
// file is present at URL
console.log('try cache.add ' + newFile);
//https://web.dev/learn/pwa/caching/
caches.open("v.1.2.2025.10")
.then(cache => {
cache.add(newFile); // it stores only one resource
//  cache.addAll(["styles.css", "app.js"]); // it stores two resources
});
} else {
console.log('404 not found ' + newFile);
// file is not present at URL
}
})
.catch((error) => {
  console.log(error)
});

}




});



});

}




// rm old cache
//https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/delete
this.addEventListener("activate", (event) => {
  const cachesToKeep = ["v.1.2.2025.10"];

  event.waitUntil(
    caches.keys().then((keyList) =>
      Promise.all(
        keyList.map((key) => {
          if (!cachesToKeep.includes(key)) {
            return caches.delete(key);
          }
        }),
      ),
    ),
  );
});




// read cache
/*
//https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#basic_architecture
const cacheFirst = async (request) => {
  const responseFromCache = await caches.match(request, {ignoreSearch: true});
  if (responseFromCache) {
    return responseFromCache;
  }
return fetch(request);
};

self.addEventListener("fetch", (event) => {
  event.respondWith(cacheFirst(event.request));
});*/




/*//https://web.dev/learn/pwa/serving
// cache first
self.addEventListener("fetch", event => {
   event.respondWith(
     caches.match(event.request, {ignoreSearch: true})
     .then(cachedResponse => {
       // It can update the cache to serve updated content on the next request
         return cachedResponse || fetch(event.request);
     }
   )
  )
});*/


//https://web.dev/learn/pwa/serving
// cache first
self.addEventListener("fetch", event => {
   event.respondWith(
     caches.match(event.request, {ignoreSearch: true})
     .then(cachedResponse => {
       // It can update the cache to serve updated content on the next request
         return cachedResponse || fetch(event.request);
     }
   )
  )
});

// read cache


